# Generated by Django 5.0.3 on 2024-03-31 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.ImageField(blank=True, default='https://live.staticflickr.com/65535/53623560975_05981be63f_m.jpg', upload_to='cars'),
        ),
    ]
